<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE languages [
  <!ELEMENT languages (language+)>
  <!ELEMENT language (abbrev | long)*>
  <!ATTLIST language id ID #REQUIRED
>
  <!ELEMENT abbrev (#PCDATA)>
  <!ATTLIST abbrev xml:lang IDREF #REQUIRED
>
  <!ELEMENT long (#PCDATA)>
  <!ATTLIST long xml:lang IDREF #REQUIRED
>
]>
<!-- Language codes and names -->
<!--
  Die Codes richten sich nach ISO 639-1. Zusätzlich sind einige Sprachen
  aus ISO 639-2 aufgenommen. Die Sprachbezeichnungen sind größtenteils
  nur Englisch vorhanden und auch nicht überall als Abkürzungen, da
  ich noch keine Copyrightfreie Quelle gefunden habe.
  
  (Ansonsten siehe:
    
    * http://www.indigo.ie/egt/standards/iso639/iso639-1-fr.html
    *
  )
-->
<languages>
  <!-- ISO 639-1 -->
  <language id="aa">
    <long xml:lang="en">afar</long>
  </language>
  <language id="ab">
    <long xml:lang="en">abkhazian</long>
  </language>
  <language id="af">
    <long xml:lang="en">afrikaans</long>
  </language>
  <language id="am">
    <long xml:lang="en">amharic</long>
  </language>
  <language id="ar">
    <long xml:lang="en">arabic</long>
  </language>
  <language id="as">
    <long xml:lang="en">assamese</long>
  </language>
  <language id="ay">
    <long xml:lang="en">aymara</long>
  </language>
  <language id="az">
    <long xml:lang="en">azerbaijani</long>
  </language>
  <language id="ba">
    <long xml:lang="en">bashkir</long>
  </language>
  <language id="be">
    <long xml:lang="en">byelorussian</long>
  </language>
  <language id="bg">
    <long xml:lang="en">bulgarian</long>
  </language>
  <language id="bh">
    <long xml:lang="en">bihari</long>
  </language>
  <language id="bi">
    <long xml:lang="en">bislama</long>
  </language>
  <language id="bn">
    <long xml:lang="en">bengali</long>
  </language>
  <language id="bo">
    <long xml:lang="en">tibetan</long>
  </language>
  <language id="br">
    <long xml:lang="en">breton</long>
  </language>
  <language id="ca">
    <long xml:lang="en">catalan</long>
  </language>
  <language id="co">
    <long xml:lang="en">corsican</long>
  </language>
  <language id="cs">
    <long xml:lang="en">czech</long>
  </language>
  <language id="cy">
    <long xml:lang="en">welsh</long>
  </language>
  <language id="da">
    <long xml:lang="en">danish</long>
  </language>
  <language id="de">
    <long xml:lang="en">german</long>
    <abbrev xml:lang="en">ger</abbrev>        
    <abbrev xml:lang="de">dt</abbrev>
    <long xml:lang="de">deutsch</long>    
  </language>
  <language id="dz">
    <long xml:lang="en">bhutani</long>
  </language>
  <language id="el">
    <long xml:lang="en">greek</long>
    <abbrev xml:lang="en">grk</abbrev>
    <abbrev xml:lang="de">griech</abbrev>
    <long xml:lang="de">griechisch</long>    
  </language>
  <language id="en">
    <long xml:lang="en">english</long>
    <abbrev xml:lang="en">en</abbrev>    
    <abbrev xml:lang="de">engl</abbrev>
    <long xml:lang="de">englisch</long>    
  </language>
  <language id="eo">
    <long xml:lang="en">esperanto</long>
  </language>
  <language id="es">
    <long xml:lang="en">spanish</long>
    <abbrev xml:lang="en">sp</abbrev>
    <abbrev xml:lang="de">span</abbrev>
    <long xml:lang="de">spanisch</long>    
  </language>
  <language id="et">
    <long xml:lang="en">estonian</long>
  </language>
  <language id="eu">
    <long xml:lang="en">basque</long>
  </language>
  <language id="fa">
    <long xml:lang="en">persian</long>
  </language>
  <language id="fi">
    <long xml:lang="en">finnish</long>
  </language>
  <language id="fj">
    <long xml:lang="en">fiji</long>
  </language>
  <language id="fo">
    <long xml:lang="en">faeroese</long>
  </language>
  <language id="fr">
    <long xml:lang="en">french</long>
    <abbrev xml:lang="en">fr</abbrev>    
    <long xml:lang="de">französisch</long>    
    <abbrev xml:lang="de">fr</abbrev>    
  </language>
  <language id="fy">
    <long xml:lang="en">frisian</long>
  </language>
  <language id="ga">
    <long xml:lang="en">irish</long>
  </language>
  <language id="gd">
    <long xml:lang="en">scots, Gaelic</long>
  </language>
  <language id="gl">
    <long xml:lang="en">galician</long>
  </language>
  <language id="gn">
    <long xml:lang="en">guarani</long>
  </language>
  <language id="gu">
    <long xml:lang="en">gujarati</long>
  </language>
  <language id="he">
    <long xml:lang="en">hebrew</long>
  </language>
  <language id="ha">
    <long xml:lang="en">hausa</long>
  </language>
  <language id="hi">
    <long xml:lang="en">hindi</long>
  </language>
  <language id="hr">
    <long xml:lang="en">croatian</long>
  </language>
  <language id="hu">
    <long xml:lang="en">hungarian</long>
  </language>
  <language id="hy">
    <long xml:lang="en">armenian</long>
  </language>
  <language id="ia">
    <long xml:lang="en">interlingua</long>
  </language>
  <language id="id">
    <long xml:lang="en">indonesian</long>
  </language>
  <language id="ie">
    <long xml:lang="en">interlingue</long>
  </language>
  <language id="ik">
    <long xml:lang="en">inupiak</long>
  </language>
  <language id="in">
    <long xml:lang="en">indonesian</long>
  </language>
  <language id="is">
    <long xml:lang="en">icelandic</long>
  </language>
  <language id="it">
    <long xml:lang="en">italian</long>
  </language>
  <language id="iu">
    <long xml:lang="en">inuktitut</long>
  </language>
  <language id="ja">
    <long xml:lang="en">japanese</long>
  </language>
  <language id="jw">
    <long xml:lang="en">javanese</long>
  </language>
  <language id="ka">
    <long xml:lang="en">georgian</long>
  </language>
  <language id="kk">
    <long xml:lang="en">kazakh</long>
  </language>
  <language id="kl">
    <long xml:lang="en">greenlandic</long>
  </language>
  <language id="km">
    <long xml:lang="en">cambodian</long>
  </language>
  <language id="kn">
    <long xml:lang="en">kannada</long>
  </language>
  <language id="ko">
    <long xml:lang="en">korean</long>
  </language>
  <language id="ks">
    <long xml:lang="en">kashmiri</long>
  </language>
  <language id="ku">
    <long xml:lang="en">kurdish</long>
  </language>
  <language id="ky">
    <long xml:lang="en">kirghiz</long>
  </language>
  <language id="la">
    <long xml:lang="en">latin</long>
    <abbrev xml:lang="en">lat</abbrev>
    <long xml:lang="de">latein</long>
    <abbrev xml:lang="de">lat</abbrev>    
  </language>
  <language id="ln">
    <long xml:lang="en">lingala</long>
  </language>
  <language id="lo">
    <long xml:lang="en">laothian</long>
  </language>
  <language id="lt">
    <long xml:lang="en">lithuanian</long>
  </language>
  <language id="lv">
    <long xml:lang="en">lettish</long>
  </language>
  <language id="mg">
    <long xml:lang="en">malagasy</long>
  </language>
  <language id="mi">
    <long xml:lang="en">maori</long>
  </language>
  <language id="mk">
    <long xml:lang="en">macedonian</long>
  </language>
  <language id="ml">
    <long xml:lang="en">malayalam</long>
  </language>
  <language id="mn">
    <long xml:lang="en">mongolian</long>
  </language>
  <language id="mo">
    <long xml:lang="en">moldavian</long>
  </language>
  <language id="mr">
    <long xml:lang="en">marathi</long>
  </language>
  <language id="ms">
    <long xml:lang="en">malay</long>
  </language>
  <language id="mt">
    <long xml:lang="en">maltese</long>
  </language>
  <language id="my">
    <long xml:lang="en">burmese</long>
  </language>
  <language id="na">
    <long xml:lang="en">nauru</long>
  </language>
  <language id="ne">
    <long xml:lang="en">nepali</long>
  </language>
  <language id="nl">
    <long xml:lang="en">dutch</long>
  </language>
  <language id="no">
    <long xml:lang="en">norwegian</long>
  </language>
  <language id="oc">
    <long xml:lang="en">occitan</long>
  </language>
  <language id="om">
    <long xml:lang="en">oromo</long>
  </language>
  <language id="or">
    <long xml:lang="en">oriya</long>
  </language>
  <language id="pa">
    <long xml:lang="en">punjabi</long>
  </language>
  <language id="pl">
    <long xml:lang="en">polish</long>
  </language>
  <language id="ps">
    <long xml:lang="en">pushto</long>
  </language>
  <language id="pt">
    <long xml:lang="en">portuguese</long>
  </language>
  <language id="qu">
    <long xml:lang="en">quechua</long>
  </language>
  <language id="rm">
    <long xml:lang="en">rhaeto-romance</long>
  </language>
  <language id="rn">
    <long xml:lang="en">kirundi</long>
  </language>
  <language id="ro">
    <long xml:lang="en">romanian</long>
  </language>
  <language id="ru">
    <long xml:lang="en">russian</long>
  </language>
  <language id="rw">
    <long xml:lang="en">kinyarwanda</long>
  </language>
  <language id="sa">
    <long xml:lang="en">sanskrit</long>
  </language>
  <language id="sd">
    <long xml:lang="en">sindhi</long>
  </language>
  <language id="sg">
    <long xml:lang="en">sangro</long>
  </language>
  <language id="sh">
    <long xml:lang="en">serbo-croatian</long>
  </language>
  <language id="si">
    <long xml:lang="en">singhalese</long>
  </language>
  <language id="sk">
    <long xml:lang="en">slovak</long>
  </language>
  <language id="sl">
    <long xml:lang="en">slovenian</long>
  </language>
  <language id="sm">
    <long xml:lang="en">samoan</long>
  </language>
  <language id="sn">
    <long xml:lang="en">shona</long>
  </language>
  <language id="so">
    <long xml:lang="en">somali</long>
  </language>
  <language id="sq">
    <long xml:lang="en">albanian</long>
  </language>
  <language id="sr">
    <long xml:lang="en">serbian</long>
  </language>
  <language id="ss">
    <long xml:lang="en">siswati</long>
  </language>
  <language id="st">
    <long xml:lang="en">sesotho</long>
  </language>
  <language id="su">
    <long xml:lang="en">sundanese</long>
  </language>
  <language id="sv">
    <long xml:lang="en">swedish</long>
  </language>
  <language id="sw">
    <long xml:lang="en">swahili</long>
  </language>
  <language id="ta">
    <long xml:lang="en">tamil</long>
  </language>
  <language id="te">
    <long xml:lang="en">tegulu</long>
  </language>
  <language id="tg">
    <long xml:lang="en">tajik</long>
  </language>
  <language id="th">
    <long xml:lang="en">thai</long>
  </language>
  <language id="ti">
    <long xml:lang="en">tigrinya</long>
  </language>
  <language id="tk">
    <long xml:lang="en">turkmen</long>
  </language>
  <language id="tl">
    <long xml:lang="en">tagalog</long>
  </language>
  <language id="tn">
    <long xml:lang="en">setswana</long>
  </language>
  <language id="to">
    <long xml:lang="en">tonga</long>
  </language>
  <language id="tr">
    <long xml:lang="en">turkish</long>
  </language>
  <language id="ts">
    <long xml:lang="en">tsonga</long>
  </language>
  <language id="tt">
    <long xml:lang="en">tatar</long>
  </language>
  <language id="tw">
    <long xml:lang="en">twi</long>
  </language>
  <language id="ug">
    <long xml:lang="en">uigur</long>
  </language>
  <language id="uk">
    <long xml:lang="en">ukrainian</long>
  </language>
  <language id="ur">
    <long xml:lang="en">urdu</long>
  </language>
  <language id="uz">
    <long xml:lang="en">uzbek</long>
  </language>
  <language id="vi">
    <long xml:lang="en">vietnamese</long>
  </language>
  <language id="vo">
    <long xml:lang="en">volapuk</long>
  </language>
  <language id="wo">
    <long xml:lang="en">wolof</long>
  </language>
  <language id="xh">
    <long xml:lang="en">xhosa</long>
  </language>
  <language id="y">
    <long xml:lang="en">yiddish</long>
  </language>
  <language id="yo">
    <long xml:lang="en">yoruba</long>
  </language>
  <language id="za">
    <long xml:lang="en">zuang</long>
  </language>
  <language id="zh">
    <long xml:lang="en">chinese</long>
  </language>
  <language id="zu">
    <long xml:lang="en">zulu</long>
  </language>  
  <!--=============  ISO 639-2 (parts) ===============-->
  <language id="gmh">
    <abbrev xml:lang="de">mhd</abbrev>
    <long xml:lang="de">mittelhochdeutsch</long>
    <abbrev xml:lang="en">MHG</abbrev>
    <long xml:lang="en">middle high german</long>    
  </language>
  <language id="goh">
    <abbrev xml:lang="de">ahd</abbrev>
    <long xml:lang="de">althochdeutsch</long>
    <abbrev xml:lang="en">OHG</abbrev>
    <long xml:lang="en">old high german</long>
  </language>
</languages>
